.TH "/Users/thibault/GitHub/CERI_software_engineering_game_1/headers/entite.h" 3 "Fri May 5 2017" "The Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/GitHub/CERI_software_engineering_game_1/headers/entite.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'competence\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBentite\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Game from the source code\&.
