.TH "/Users/thibault/GitHub/CERI_software_engineering_game_1/headers/monstre.h" 3 "Fri May 5 2017" "The Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/GitHub/CERI_software_engineering_game_1/headers/monstre.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/entite\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmonstre\fP"
.br
.RI "Classe créant un monstre en mémoire\&. hérite des propriétés ainsi que des attributs de la classe entite\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Game from the source code\&.
